In [34]:
import pandas as pd

dtm_regex_URL = "https://github.com/Magallanes-at-UTDT/texts/raw/main/data/processed/DocumentTermMatrix_Regex_Counts.parquet"

dtm_regex = pd.read_parquet(dtm_regex_URL)

In [35]:
dtm_regex.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, AhoraNacion to RenovacionPopular
Columns: 7825 entries, 0e5 to útil
dtypes: int64(7825)
memory usage: 366.8+ KB

In [36]:
dtm_regex.index

Index(['AhoraNacion', 'BuenGobierno', 'FuerzaPopular', 'JuntosPorElPeru',
       'Obras', 'RenovacionPopular'],
      dtype='object')

calculate the total frequency of every term across the corpus:

In [37]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()

dtm_regex_tfidf = pd.DataFrame(
    tfidf.fit_transform(dtm_regex).toarray(),
    index=dtm_regex.index,
    columns=dtm_regex.columns
)

In [38]:
dtm_regex_tfidf.head()

,0e5,10mil,120k,12h,1818,1824,1907,1950,1960,1970,...,óptico,óptimo,óptimos,órbita,órdén,órgano,últimamente,únicamente,único,útil
AhoraNacion,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.003663,0.001764,0.00000,0.000000,0.002349,0.000000,0.000000,0.009036,0.000000
BuenGobierno,0.00266,0.000000,0.00266,0.005321,0.00266,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.010908,0.000000,0.000000,0.00266,0.000000,0.007086,0.000000,0.000000,0.024534,0.002182
FuerzaPopular,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.002046,0.000000,0.000000,0.000000,...,0.005033,0.005665,0.000000,0.00000,0.002046,0.004541,0.000000,0.001678,0.025155,0.000000
JuntosPorElPeru,0.00000,0.041391,0.00000,0.000000,0.00000,0.003449,0.000000,0.010348,0.003449,0.003449,...,0.000000,0.002388,0.000000,0.00000,0.000000,0.003062,0.003449,0.016970,0.015904,0.000000
Obras,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.005960,0.000000,0.000000,0.041272,0.011010

> Raw counts measure frequency, whereas TF-IDF measures importance relative to the corpus. Consequently, TF-IDF often downweights common terms (e.g., estado, economía) while highlighting terms that distinguish one document from the others.

In [39]:
dtm_regex_tfidf[["economía", "salud", "educación"]]

                   economía     salud  educación
AhoraNacion        0.053240  0.082992   0.053240
BuenGobierno       0.029524  0.057866   0.049600
FuerzaPopular      0.043590  0.108976   0.103527
JuntosPorElPeru    0.056651  0.191388   0.102584
Obras              0.041719  0.125158   0.101319
RenovacionPopular  0.021181  0.137675   0.037066

In [40]:
dtm_regex[["economía", "salud", "educación"]]

                   economía  salud  educación
AhoraNacion              68    106         68
BuenGobierno             25     49         42
FuerzaPopular            48    120        114
JuntosPorElPeru          37    125         67
Obras                     7     21         17
RenovacionPopular         4     26          7

In [41]:
from pathlib import Path

PROCESSED_DIR = Path("data/processed")


dtm_regex_tfidf.to_parquet(
    PROCESSED_DIR / "DocumentTermMatrix_Regex_TFIDF.parquet"
)