In [3]:
import pandas as pd

DTM_URL = (
    "https://github.com/Magallanes-at-UTDT/texts/raw/main/"
    "data/processed/dtm_counts.parquet"
)

dtm = pd.read_parquet(DTM_URL)

In [4]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()

dtm_tfidf = tfidf.fit_transform(dtm)

In [5]:
dtm_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21904 stored elements and shape (6, 11020)>

In [11]:
dtm_tfidf[:1].toarray()

array([[0.        , 0.        , 0.00227053, ..., 0.        , 0.        ,
        0.        ]], shape=(1, 11020))

In [12]:
dtm[:1]

,0270,0e5,1000,1010,1053,10mil,1131,1133,1151,1170,...,último,últimos,única,únicamente,únicas,único,únicos,útil,útiles,⅓
party,,,,,,,,,,,,,,,,,,,,,
AhoraNacion,0,0,2,1,0,0,1,1,0,0,...,1,11,2,0,1,5,2,0,0,0

In [13]:
dtm_tfidf_df = pd.DataFrame(
    dtm_tfidf.toarray(),
    index=dtm.index,
    columns=dtm.columns
)
##
dtm_tfidf_df.iloc[:1]

,0270,0e5,1000,1010,1053,10mil,1131,1133,1151,1170,...,último,últimos,única,únicamente,únicas,único,únicos,útil,útiles,⅓
party,,,,,,,,,,,,,,,,,,,,,
AhoraNacion,0.0,0.0,0.002271,0.001914,0.0,0.0,0.001914,0.001914,0.0,0.0,...,0.001135,0.009344,0.001961,0.0,0.001325,0.005676,0.003138,0.0,0.0,0.0

In [14]:
dtm[["economía", "salud", "educación"]]

                   economía  salud  educación
party
AhoraNacion              63    106         68
BuenGobierno             20     49         42
FuerzaPopular            44    120        114
JuntosPorElPeru          32    125         67
Obras                     9     21         17
RenovacionPopular         4     26          7

In [15]:
dtm_tfidf_df[["economía", "salud", "educación"]]

                   economía     salud  educación
party
AhoraNacion        0.053515  0.090042   0.057763
BuenGobierno       0.026706  0.065429   0.056082
FuerzaPopular      0.043447  0.118493   0.112568
JuntosPorElPeru    0.052984  0.206970   0.110936
Obras              0.055275  0.128975   0.104408
RenovacionPopular  0.021503  0.139772   0.037631

In [16]:
dtm_tfidf_df.loc["AhoraNacion"].sort_values(ascending=False).head(20)

nacional       0.278619
desarrollo     0.212362
porcentaje     0.193137
meta           0.160546
estrategia     0.152126
sistema        0.150353
país           0.140159
perú           0.135062
estratégico    0.134314
objetivo       0.132353
problema       0.123170
servicios      0.120622
cuál           0.116730
acceso         0.110428
plan           0.100235
uso            0.095988
número         0.095988
sostenible     0.095138
ahora          0.094151
nación         0.092157
Name: AhoraNacion, dtype: float64

In [17]:
dtm.loc["AhoraNacion"].sort_values(ascending=False).head(20)

nacional       328
desarrollo     250
porcentaje     197
meta           189
sistema        177
país           165
perú           159
problema       145
servicios      142
estratégico    137
objetivo       135
estrategia     134
acceso         130
plan           118
número         113
uso            113
sostenible     112
salud          106
social         104
gestión        101
Name: AhoraNacion, dtype: int64

So if you have six parties:

| Party | Document    |
| ----- | ----------- |
| A     | Manifesto A |
| B     | Manifesto B |
| C     | Manifesto C |
| D     | Manifesto D |
| E     | Manifesto E |
| F     | Manifesto F |

then, when computing the TF–IDF weights for **Party A**, the algorithm asks:

1. **TF:** How often does this word appear in Party A's manifesto?
2. **IDF:** In how many of the **six manifestos** does this word appear?

A word that appears in **all six parties** receives a much smaller IDF than a word appearing in only one or two parties.


> Unlike raw word counts, TF–IDF evaluates each document **relative to the rest of the corpus**. The weight assigned to a word depends not only on how frequently it appears in one party's manifesto, but also on how common that word is across all party manifestos.